# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_meta_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sites',
        ),
    ]
